# Generated by Django 3.0 on 2019-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('borrado', 'Borrado')], default='habilitado', max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
