# Generated by Django 3.0 on 2019-12-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Cliente', verbose_name='el cliente que realiza la operación')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Evento', verbose_name='el evento al que asiste el cliente')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
