# Generated by Django 3.0 on 2019-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20191209_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='distrito',
            field=models.CharField(choices=[('surco', 'Surco'), ('barranco', 'Barranco')], default='surco', max_length=10),
        ),
    ]
