# Generated by Django 3.0 on 2019-12-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_auto_20191209_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Cliente', verbose_name='el cliente que pertenece a este perfil')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil', verbose_name='el perfil asociado')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
